language: node_js
node_js:
  - 5.8.0

before_install:
  # in the before_install context we are responsible for all the dependencies
  - npm install qnit
  #
  # use npm2, npm@1.2.30 that travis uses for node-v0.8 breaks downloading from registry.npmjs.org: tlsv1 s23_clnt.c:658
  # sometimes node-v5.8.0 gets npm-v2.15.0 pre-installed into ./node_modules, else in ~/.nvm/versions/*/bin
  # other nvm node versions overwerite it, so save this copy
  # Do not reinstall, it can break (module not found) when overwriting itself
  #
  - mkdir -p $HOME/bin $HOME/lib2 $HOME/lib
  # - echo prefix=$HOME >> $HOME/.npmrc
  - test -x ./node_modules/.bin/npm || npm install npm@2.15.0
  # - sed -ie /^prefix=/d $HOME/.npmrc
  # - test -d $HOME/lib/node_modules && cp -rpf $HOME/lib/node_modules $HOME/lib2/ || true
  - test -d ./node_modules && cp -rpf ./node_modules $HOME/lib2/ || true
  - ln -sf ../lib2/node_modules/qnit/bin/qnit $HOME/bin/qnit
  - ln -sf ../lib2/node_modules/npm/bin/npm-cli.js $HOME/bin/npm2
  - npm2 --version
  - npm2 install .
  #
  # nvm install 0.6 && npm2 -v && node -v && npm2 test -- travis-ci.com breaks on node-v0.6
  - nvm install 0.8.28 && npm2 -v && node -v && npm2 test
  - nvm install 0.10 && npm2 -v && node -v && npm2 test
  - nvm install 4 && npm2 -v && node -v && npm2 test
  #- nvm install 5.12 && npm2 -v && node -v && npm2 test -- race condition?
  - nvm install 12 && npm2 -v && node -v && npm2 test
  - nvm install 16 && npm2 -v && node -v && npm2 test
  #- nvm install 18 && npm2 -v && node -v && npm2 test -- travis-ci.com has wrong version of glibc
  - nvm install 5.8.0

after_success:
  - if [ `node -v` != "v5.8.0" ]; then exit; fi
  - npm install -g nyc@8.4.0 coveralls@3.0.2 codecov
  - npm run coverage && codecov
  - nyc report -r text-lcov | coveralls
