language: node_js
node_js:
  - 5.8.0

before_install:
  # use npm2, npm@1.2.30 that travis uses for node-v0.8 breaks
  - mkdir -p $HOME/bin $HOME/lib
  - npm install qnit npm@2.15.0
  - cp -rp node_modules $HOME/lib/
  - ln -sf ../lib/node_modules/.bin/qnit $HOME/bin/qnit
  - ln -sf ../lib/node_modules/.bin/npm $HOME/bin/npm2
  # test other node versions of interest too
  # travis uses nvm to install npm-v1 for node-v0.8, which can no longer download from registry.npmjs.org:
  # npm ERR! Error: 139905814947648:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol ... s23_clnt.c:658
  # So test with 0.8 explicitly from inside the 5.8.0 test run
  # nvm install 0.6 && npm2 -v && node -v && npm2 test -- travis.ci breaks on node-v0.6, skip for now
  - nvm install 0.8.28 && npm2 -v && node -v && npm2 test
  - nvm install 0.10 && npm2 -v && node -v && npm2 test
  - nvm install 4 && npm2 -v && node -v && npm2 test
  - nvm install 5.12 && npm2 -v && node -v && npm2 test
  - nvm install 12 && npm2 -v && node -v && npm2 test
  - nvm install 16 && npm2 -v && node -v && npm2 test
  - nvm install 5.8.0

after_success:
  - if [ `node -v` != "v5.8.0" ]; then exit; fi
  - npm install -g nyc@8.4.0 coveralls@3.0.2
  - npm run coverage
  - nyc report -r text-lcov | coveralls
