language: node_js
node_js:
  #- 0.6 -- travis.ci breaks on node-v0.6, skip for now
  #- 0.8.28 -- travis.ci installs npm1 for v0.8, which can no longer download from npmjs.org
  # However, npm-v2.15.0 works with node-v0.8.28
  #- 0.10
  #- 4
  - 5.8.0
  #- 5.12.0
  #- 10
  #- 14
  #- 15
before_install:
  - mkdir $HOME/bin $HOME/lib
  - echo prefix=$HOME >> $HOME/.npmrc
  - npm install -g qnit npm@2.15.0
  #- [ `node -v` = "v5.8.0" ] && nvm 0.8.28 && $HOME/bin/npm test && nvm 5.8.0
after_success:
  - if [ `node -p 'process.version.slice(0, 4)'` != "v5.8" ]; then exit; fi
  - npm install -g nyc coveralls
  - nyc -r text --reporter lcov npm test
  - nyc report -r text-lcov | coveralls
