language: node_js
node_js:
  #- 0.6 -- travis.ci breaks on node-v0.6, skip for now
  - 0.8
  - 0.10
  - 4
  - 5.8.0
  - 5.12.0
  - 10
  - 12
  - 15
before_install:
  - npm install npm@2.15.0
  - npm install -g qnit
after_success:
  - if [ `node -p 'process.version.slice(0, 4)'` != "v5.8" ]; then exit; fi
  - npm install -g nyc coveralls
  - nyc -r text --reporter lcov npm test
  - nyc report -r text-lcov | coveralls
